DROP TABLE FASTFERIA.saldos;
DROP TABLE FASTFERIA.recargas;
DROP TABLE FASTFERIA.metodo_pago;
DROP TABLE FASTFERIA.vent_local;
DROP TABLE FASTFERIA.vent_extran;
DROP TABLE FASTFERIA.seguimiento;
DROP TABLE FASTFERIA.reportes;
DROP TABLE FASTFERIA.report_venta;
DROP TABLE FASTFERIA.detall_compra;
DROP TABLE FASTFERIA.proces_venta;
DROP TABLE FASTFERIA.proces_pedido;
DROP TABLE FASTFERIA.transporte;
DROP TABLE FASTFERIA.pedido;
DROP TABLE FASTFERIA.productos;
DROP TABLE FASTFERIA.report_merma;
DROP TABLE FASTFERIA.contratos;
DROP TABLE FASTFERIA.usuarios;

CREATE TABLE FASTFERIA.usuarios (
    id_usr                 NUMBER(11) GENERATED by default on null as IDENTITY,
    rut_usr                VARCHAR2(9),
    nombre                 VARCHAR2(30) NOT NULL,
    apellido_p             VARCHAR2(30) NOT NULL,
    apellido_m             VARCHAR2(30) NOT NULL,
    direccion              VARCHAR2(100) NOT NULL,
    telefono               NUMBER(11) NOT NULL,
    correo                 VARCHAR2(150) NOT NULL,
    foto                   BLOB,
    contrasena             VARCHAR2(40) NOT NULL,
    rol                    NUMBER(3)
);

ALTER TABLE FASTFERIA.usuarios ADD CONSTRAINT usuarios_pk PRIMARY KEY ( id_usr );

CREATE TABLE FASTFERIA.contratos (
    id_contrat              NUMBER(11) GENERATED by default on null as IDENTITY,
    usuarios_id            NUMBER(11) NOT NULL,
    emision_contrat         DATE NOT NULL,
    fin_contrat             DATE NOT NULL,
    estado       		    NUMBER(1) NOT NULL,
    foto    			    BLOB
);

ALTER TABLE FASTFERIA.contratos ADD CONSTRAINT contratos_pk PRIMARY KEY ( id_contrat );

CREATE TABLE FASTFERIA.report_merma (
    id_merma                    NUMBER(11) GENERATED by default on null as IDENTITY,
    fecha_merma                 DATE NOT NULL,
    descrip_merma               VARCHAR2(40) NOT NULL,
    usuarios_id   NUMBER(11) NOT NULL
);

ALTER TABLE FASTFERIA.report_merma ADD CONSTRAINT report_merma_pk PRIMARY KEY ( id_merma );

CREATE TABLE FASTFERIA.productos (
    id_prod                     NUMBER(11) GENERATED by default on null as IDENTITY,
    nom_prod                    VARCHAR2(20) NOT NULL,
    precio_prod                 NUMBER(9) NOT NULL,
    desc_prod                   VARCHAR2(200) NOT NULL,
    stock_prod                  NUMBER(9) NOT NULL,
    usuarios_id   NUMBER(11) NOT NULL,
    foto   			BLOB

);

ALTER TABLE FASTFERIA.productos ADD CONSTRAINT productos_pk PRIMARY KEY ( id_prod );

CREATE TABLE FASTFERIA.transporte (
    id_trans                    NUMBER(11) GENERATED by default on null as IDENTITY,
    tip_transporte              VARCHAR2(15) NOT NULL,
    tamano_trans                NUMBER(8) NOT NULL,
    capacidad_trans             NUMBER(8) NOT NULL,
    refrigeracion_trans         NUMBER(1) NOT NULL,
    usuarios_id   NUMBER(11) NOT NULL,
    foto    	        	BLOB,
    patente 			VARCHAR2(10) NOT NULL
);

ALTER TABLE FASTFERIA.transporte ADD CONSTRAINT transporte_pk PRIMARY KEY ( id_trans );

CREATE TABLE FASTFERIA.pedido (
    id_ped                      NUMBER(11) GENERATED by default on null as IDENTITY,
    tipo                        VARCHAR2(200) NOT NULL,
    cantidad			        NUMBER(8) NOT NULL,
    fecha                       DATE NOT NULL,
    descrip                     VARCHAR2(200) NOT NULL,
    usuarios_id                 NUMBER(11) NOT NULL,
    productos                   NUMBER(8) NULL,
    estado_admin		        NUMBER(1) NOT NULL,
    estado_productor		    NUMBER(1) NOT NULL,
    refrigeracion 		        NUMBER(1) NOT NULL,
    estado_edit_user		    NUMBER(1) NOT NULL,
    estado_edit_admin		    NUMBER(1) NOT NULL
);

ALTER TABLE FASTFERIA.pedido ADD CONSTRAINT pedido_pk PRIMARY KEY ( id_ped );

CREATE TABLE FASTFERIA.proces_pedido (
    id_proc_pedido        NUMBER(11) GENERATED by default on null as IDENTITY,
    transportes           NUMBER(7) NOT NULL,
    pedido         NUMBER(8) NOT NULL,
    estado_proceso	      NUMBER(1) NOT NULL,
    estado_seguimiento    NUMBER(1) NOT NULL,
    estado_proces_venta	  NUMBER(1) NOT NULL
);

ALTER TABLE FASTFERIA.proces_pedido ADD CONSTRAINT proces_pedido_pk PRIMARY KEY ( id_proc_pedido );

CREATE TABLE FASTFERIA.proces_venta (
    id_proc_venta                   NUMBER(11) GENERATED by default on null as IDENTITY,
    proces_pedido                   NUMBER(8) NOT NULL,
    estado_pago_cliente 	        NUMBER(1) NOT NULL,
    estado_pago_product	            NUMBER(1)  NOT NULL,
    estado_pago_transport	        NUMBER(1) NOT NULL,
    estado_venta		            NUMBER(1) NOT NULL,
    estado_detalle		            NUMBER(1) NOT NULL
);

ALTER TABLE FASTFERIA.proces_venta ADD CONSTRAINT proces_venta_pk PRIMARY KEY ( id_proc_venta );

CREATE TABLE FASTFERIA.detall_compra (
    id_detall                   NUMBER(11) GENERATED by default on null as IDENTITY,
    proces_venta                NUMBER(9) NOT NULL,
    fecha_detall                DATE NOT NULL,
    nom_producto                VARCHAR2(15) NOT NULL,
    cost_producto               NUMBER(7) NOT NULL,
    cantidad                    NUMBER(8) NOT NULL,
    iva_producto                NUMBER(7) NOT NULL,
    total_compra                NUMBER(7) NOT NULL
);

CREATE UNIQUE INDEX detall_compra__idx ON
    FASTFERIA.detall_compra (
        proces_venta
    ASC );

ALTER TABLE FASTFERIA.detall_compra ADD CONSTRAINT detall_compra_pk PRIMARY KEY ( id_detall );

CREATE TABLE FASTFERIA.report_venta (
    id_report_vent               NUMBER(11) GENERATED by default on null as IDENTITY,
    prod_venta                   VARCHAR2(20) NOT NULL,
    cant_venta                   NUMBER(8) NOT NULL,
    total_venta                  NUMBER(8) NOT NULL,
    proces_venta   NUMBER(9) NOT NULL
);

ALTER TABLE FASTFERIA.report_venta ADD CONSTRAINT report_venta_pk PRIMARY KEY ( id_report_vent );

CREATE TABLE FASTFERIA.reportes (
    id_report                   NUMBER(11) GENERATED by default on null as IDENTITY,
    fecha_report                DATE NOT NULL,
    tip_report                  VARCHAR2(15) NOT NULL,
    user_report                 VARCHAR2(15) NOT NULL,
    descrip_report              VARCHAR2(30) NOT NULL,
    usuarios_id   NUMBER(11) NOT NULL
);

ALTER TABLE FASTFERIA.reportes ADD CONSTRAINT reportes_pk PRIMARY KEY ( id_report );

CREATE TABLE FASTFERIA.seguimiento (
    id_seguimiento                 NUMBER(11) GENERATED by default on null as IDENTITY,
    est_seguimiento                VARCHAR2(20) NOT NULL,
    pedido                  NUMBER(8) NOT NULL,
    proces_pedido   NUMBER(8) NOT NULL
);

ALTER TABLE FASTFERIA.seguimiento ADD CONSTRAINT seguimiento_pk PRIMARY KEY ( id_seguimiento );

CREATE TABLE FASTFERIA.vent_extran (
    id_vent_ex                   NUMBER(11) GENERATED by default on null as IDENTITY,
    proces_venta   NUMBER(9) NOT NULL,
    nom_cli                      VARCHAR2(30) NOT NULL,
    ape_cli                      VARCHAR2(30) NOT NULL,
    email                        VARCHAR2(50) NOT NULL,
    pais			 VARCHAR2(30) NOT NULL,
    direc_cli 			 VARCHAR2(50) NOT NULL,
    num_calle 			 NUMBER(8) NOT NULL,
    depto 			 NUMBER(8) NOT NULL,
    localidad 			 VARCHAR2(50) NOT NULL
);

ALTER TABLE FASTFERIA.vent_extran ADD CONSTRAINT vent_extran_pk PRIMARY KEY ( id_vent_ex );

CREATE TABLE FASTFERIA.vent_local (
    id_vent_loc                  NUMBER(11) GENERATED by default on null as IDENTITY,
    proces_venta   NUMBER(9) NOT NULL,
    nom_cli                      VARCHAR2(30) NOT NULL,
    ape_cli                      VARCHAR2(30) NOT NULL,
    email                        VARCHAR2(50) NOT NULL,
    direc_cli 			 VARCHAR2(50) NOT NULL,
    num_calle 			 NUMBER(8) NOT NULL,
    depto 			 NUMBER(8) NOT NULL,
    region 			 VARCHAR2(50) NOT NULL,
    comuna 			 VARCHAR2(50) NOT NULL
);

ALTER TABLE FASTFERIA.vent_local ADD CONSTRAINT vent_local_pk PRIMARY KEY ( id_vent_loc );

CREATE TABLE FASTFERIA.metodo_pago(
    id_pago                     NUMBER(11) GENERATED by default on null as IDENTITY,
    usuarios_id  NUMBER(11) NOT NULL,
    tipo_cuenta      		VARCHAR2(20) NOT NULL,
    numero_cuenta   		NUMBER(20) NOT NULL,
    tipo_banco      		VARCHAR2(20) NOT NULL,
    nombre_titular		VARCHAR2(20) NOT NULL
);

ALTER TABLE FASTFERIA.metodo_pago ADD CONSTRAINT metodo_pago_pk PRIMARY KEY ( id_pago );

CREATE TABLE FASTFERIA.recargas(
    id_recarga                  NUMBER(11) GENERATED by default on null as IDENTITY,
    metodo_pago         NUMBER(8) NOT NULL,
    saldo_recargado      	NUMBER(20) NOT NULL
);

ALTER TABLE FASTFERIA.recargas ADD CONSTRAINT recargas_pk PRIMARY KEY ( id_recarga );

CREATE TABLE FASTFERIA.saldos(
    id_saldo                    NUMBER(11) GENERATED by default on null as IDENTITY,
    usuarios_id   NUMBER(11) NOT NULL,
    recargas         NUMBER(8),
    saldo_total      	        NUMBER(20)
);

ALTER TABLE FASTFERIA.saldos ADD CONSTRAINT saldos_pk PRIMARY KEY ( id_saldo );

ALTER TABLE FASTFERIA.saldos	
    ADD CONSTRAINT saldos_recarga_fk FOREIGN KEY ( recargas )
        REFERENCES FASTFERIA.recargas ( id_recarga );

ALTER TABLE FASTFERIA.saldos
    ADD CONSTRAINT saldos_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.recargas
    ADD CONSTRAINT recargas_metodo_pago_fk FOREIGN KEY ( metodo_pago )
        REFERENCES FASTFERIA.metodo_pago ( id_pago );

ALTER TABLE FASTFERIA.metodo_pago
    ADD CONSTRAINT metodo_pago_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.contratos
    ADD CONSTRAINT contratos_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.detall_compra
    ADD CONSTRAINT detall_compra_proces_venta_fk FOREIGN KEY ( proces_venta )
        REFERENCES FASTFERIA.proces_venta ( id_proc_venta );

ALTER TABLE FASTFERIA.pedido
    ADD CONSTRAINT pedido_productos_fk FOREIGN KEY ( productos )
        REFERENCES FASTFERIA.productos ( id_prod );

ALTER TABLE FASTFERIA.pedido
    ADD CONSTRAINT pedido_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.proces_pedido
    ADD CONSTRAINT proces_pedido_fk FOREIGN KEY ( pedido )
        REFERENCES FASTFERIA.pedido ( id_ped );

ALTER TABLE FASTFERIA.proces_pedido
    ADD CONSTRAINT proces_pedido_transporte_fk FOREIGN KEY ( transportes )
        REFERENCES FASTFERIA.transporte ( id_trans );

ALTER TABLE FASTFERIA.proces_venta
    ADD CONSTRAINT proces_venta_proces_pedido_fk FOREIGN KEY ( proces_pedido )
        REFERENCES FASTFERIA.proces_pedido ( id_proc_pedido );

ALTER TABLE FASTFERIA.productos
    ADD CONSTRAINT productos_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.report_merma
    ADD CONSTRAINT report_merma_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.report_venta
    ADD CONSTRAINT report_venta_proces_venta_fk FOREIGN KEY ( proces_venta )
        REFERENCES FASTFERIA.proces_venta ( id_proc_venta );

ALTER TABLE FASTFERIA.reportes
    ADD CONSTRAINT reportes_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.seguimiento
    ADD CONSTRAINT seguimiento_pedido_fk FOREIGN KEY ( pedido )
        REFERENCES FASTFERIA.pedido ( id_ped );

ALTER TABLE FASTFERIA.seguimiento
    ADD CONSTRAINT seguimiento_proces_pedido_fk FOREIGN KEY ( proces_pedido )
        REFERENCES FASTFERIA.proces_pedido ( id_proc_pedido );

ALTER TABLE FASTFERIA.transporte
    ADD CONSTRAINT transporte_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES FASTFERIA.usuarios ( id_usr );

ALTER TABLE FASTFERIA.vent_extran
    ADD CONSTRAINT vent_extran_proces_venta_fk FOREIGN KEY ( proces_venta )
        REFERENCES FASTFERIA.proces_venta ( id_proc_venta );

ALTER TABLE FASTFERIA.vent_local
    ADD CONSTRAINT vent_local_proces_venta_fk FOREIGN KEY ( proces_venta )
        REFERENCES FASTFERIA.proces_venta ( id_proc_venta );
        