# Generated by Django 4.1.2 on 2022-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('rut_person', models.CharField(max_length=20)),
                ('phone_contrat', models.IntegerField()),
                ('emision_contrat', models.DateField()),
                ('fin_contrat', models.DateField()),
                ('estado', models.BooleanField()),
                ('foto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallCompra',
            fields=[
                ('id_detall', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_detall', models.DateField()),
                ('nom_producto', models.CharField(max_length=15)),
                ('cost_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('iva_producto', models.IntegerField()),
                ('total_compra', models.IntegerField()),
            ],
            options={
                'db_table': 'detall_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('numero_cuenta', models.BigIntegerField()),
                ('tipo_banco', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descrip', models.CharField(max_length=200)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('estado_admin', models.BooleanField()),
                ('estado_productor', models.BooleanField()),
                ('refrigeracion', models.BooleanField()),
                ('estado_edit_user', models.BooleanField()),
                ('estado_edit_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesPedido',
            fields=[
                ('id_proc_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_proceso', models.BooleanField()),
                ('estado_seguimiento', models.BooleanField()),
                ('estado_proces_venta', models.BooleanField()),
            ],
            options={
                'db_table': 'proces_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesVenta',
            fields=[
                ('id_proc_venta', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pago_cliente', models.BooleanField()),
                ('estado_pago_product', models.BooleanField()),
                ('estado_pago_transport', models.BooleanField()),
                ('estado_venta', models.BooleanField()),
                ('estado_detalle', models.BooleanField()),
            ],
            options={
                'db_table': 'proces_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=20)),
                ('precio_prod', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=200)),
                ('stock_prod', models.IntegerField()),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('foto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recargas',
            fields=[
                ('id_recarga', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_recargado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'recargas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_report', models.DateField()),
                ('tip_report', models.CharField(max_length=15)),
                ('user_report', models.CharField(max_length=15)),
                ('descrip_report', models.CharField(max_length=30)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMerma',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_merma', models.DateField()),
                ('descrip_merma', models.CharField(max_length=40)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
            ],
            options={
                'db_table': 'report_merma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportVenta',
            fields=[
                ('id_report_vent', models.AutoField(primary_key=True, serialize=False)),
                ('prod_venta', models.CharField(max_length=20)),
                ('cant_venta', models.IntegerField()),
                ('total_venta', models.IntegerField()),
            ],
            options={
                'db_table': 'report_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id_saldo', models.AutoField(primary_key=True, serialize=False)),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('saldo_total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saldos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('est_seguimiento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('tip_transporte', models.CharField(max_length=15)),
                ('tamano_trans', models.IntegerField()),
                ('capacidad_trans', models.IntegerField()),
                ('refrigeracion_trans', models.BooleanField()),
                ('usuarios_usuarios_id_user', models.IntegerField()),
                ('foto', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentExtran',
            fields=[
                ('id_vent_ex', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=30)),
                ('ape_cli', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('direc_cli', models.CharField(max_length=50)),
                ('num_calle', models.IntegerField()),
                ('depto', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vent_extran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentLocal',
            fields=[
                ('id_vent_loc', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=30)),
                ('ape_cli', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('direc_cli', models.CharField(max_length=50)),
                ('num_calle', models.IntegerField()),
                ('depto', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vent_local',
                'managed': False,
            },
        ),
    ]
