# Generated by Django 4.1.1 on 2022-10-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarios_id_user', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('num_calle', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('foto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
