# Generated by Django 4.1.1 on 2022-11-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('productor', 'Productor'), ('interno', 'Interno'), ('externo', 'Externo'), ('consultor', 'Consultor'), ('transportista', 'Transportista')], default='externo', max_length=50),
        ),
    ]
